export { default as Banner } from "../components/Banner"
export { default as Property } from "../components/Property"
export { default as Layout } from "../components/Layout"
export { default as Navbar } from "../components/Navbar"
export { default as Footer } from "../components/Footer"